-- Add each break's orientation: the compass bearing it faces out to sea (the
-- direction good swell arrives from). Used by the surf model for offshore/onshore
-- wind and swell-angle matching. Approximate; idempotent (re-runnable).
ALTER TABLE spots ADD COLUMN IF NOT EXISTS orientation INTEGER;

UPDATE spots AS s SET orientation = v.o
FROM (VALUES
  ('Matosinhos', 285),
  ('Espinho', 285),
  ('Figueira da Foz (Cabedelo)', 285),
  ('Nazaré (Praia do Norte)', 290),
  ('Peniche (Supertubos)', 250),
  ('Ericeira (Ribeira d''Ilhas)', 285),
  ('Guincho', 290),
  ('Carcavelos', 200),
  ('Costa da Caparica', 250),
  ('Arrifana', 280),
  ('Praia do Amado', 275),
  ('Sagres (Tonel)', 250),
  ('Pipeline (Oahu)', 340),
  ('Teahupo''o (Tahiti)', 215),
  ('Jeffreys Bay', 210),
  ('Uluwatu (Bali)', 225),
  ('Mavericks', 290),
  ('Cloudbreak (Fiji)', 225),
  ('Hossegor', 285),
  ('Mundaka', 315),
  ('Trestles', 225),
  ('Bells Beach', 200),
  ('Puerto Escondido', 200),
  ('Superbank (Snapper)', 70),
  ('Thurso East', 350),
  ('Bundoran (The Peak)', 300),
  ('Fistral Beach', 280),
  ('Lacanau', 285),
  ('La Torche', 260),
  ('Zarautz', 350),
  ('Guethary', 310),
  ('El Quemao', 330),
  ('Steamer Lane', 210),
  ('Ocean Beach (SF)', 270),
  ('Rincon (California)', 190),
  ('Malibu (First Point)', 200),
  ('Blacks Beach', 265),
  ('The Wedge', 200),
  ('Montauk', 160),
  ('Cape Hatteras', 120),
  ('Tofino (Cox Bay)', 250),
  ('Pavones', 200),
  ('Playa Hermosa (CR)', 230),
  ('Salsa Brava', 60),
  ('Rincon (Puerto Rico)', 300),
  ('Anchor Point', 300),
  ('Taghazout (Panorama)', 280),
  ('Skeleton Bay', 220),
  ('Dungeons', 250),
  ('Muizenberg', 135),
  ('Padang Padang (Bali)', 225),
  ('Keramas (Bali)', 110),
  ('Desert Point (Lombok)', 225),
  ('G-Land (Grajagan)', 160),
  ('Lagundri Bay (Nias)', 185),
  ('Arugam Bay', 135),
  ('Cloud 9 (Siargao)', 70),
  ('Margaret River', 230),
  ('Kirra', 80),
  ('Burleigh Heads', 90),
  ('Raglan (Manu Bay)', 250),
  ('Shipsterns Bluff', 185),
  ('Honolua Bay (Maui)', 315)
) AS v(name, o)
WHERE s.name = v.name;
