-- Spot catalog seed: adds region/description/featured columns and upserts the
-- full set of surf breaks. Idempotent: keyed on a unique index over name, so
-- re-running updates existing rows (and keeps their ids / favorites intact).
ALTER TABLE spots ADD COLUMN IF NOT EXISTS region TEXT;
ALTER TABLE spots ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE spots ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT false;
CREATE UNIQUE INDEX IF NOT EXISTS spots_name_uidx ON spots (name);

INSERT INTO spots (name, lat, lon, region, description, featured) VALUES
  ('Matosinhos', 41.183, -8.702, 'Europe', 'Mellow city beach break near Porto, great for learning.', false),
  ('Espinho', 41.006, -8.646, 'Europe', 'Consistent beach break south of Porto with jetty peaks.', false),
  ('Figueira da Foz (Cabedelo)', 40.14, -8.875, 'Europe', 'Powerful left off the jetty, one of Portugal''s best.', false),
  ('Nazaré (Praia do Norte)', 39.605, -9.085, 'Europe', 'Home of the biggest waves ever surfed, fed by a deep canyon.', true),
  ('Peniche (Supertubos)', 39.345, -9.367, 'Europe', 'Portugal''s premier barrelling beach break, a contest staple.', true),
  ('Ericeira (Ribeira d''Ilhas)', 38.996, -9.421, 'Europe', 'Long right point in Europe''s only World Surfing Reserve.', false),
  ('Guincho', 38.733, -9.475, 'Europe', 'Windy, punchy beach break under the Sintra hills.', false),
  ('Carcavelos', 38.677, -9.337, 'Europe', 'Lisbon''s city beach break, hollow on the right swell.', false),
  ('Costa da Caparica', 38.64, -9.235, 'Europe', 'Long stretch of shifting beach-break peaks near Lisbon.', false),
  ('Arrifana', 37.294, -8.867, 'Europe', 'Sheltered Algarve bay with a quality right point.', false),
  ('Praia do Amado', 37.166, -8.906, 'Europe', 'Exposed west-Algarve beach break, reliable and fun.', false),
  ('Sagres (Tonel)', 37.02, -8.951, 'Europe', 'West-facing beach break that catches every scrap of swell.', false),
  ('Pipeline (Oahu)', 21.665, -158.053, 'Oceania & Pacific', 'The heaviest, most photographed barrel on earth over shallow reef.', true),
  ('Teahupo''o (Tahiti)', -17.847, -149.267, 'Oceania & Pacific', 'A thick, below-sea-level slab, as perfect as it is deadly.', true),
  ('Jeffreys Bay', -34.049, 24.909, 'Africa', 'Long, fast, world-class right-hand point in South Africa.', true),
  ('Uluwatu (Bali)', -8.815, 115.088, 'Asia', 'Iconic Bali reef point with long walls beneath a clifftop temple.', true),
  ('Mavericks', 37.495, -122.5, 'North America', 'Cold, giant Californian big-wave reef that only wakes on huge swells.', true),
  ('Cloudbreak (Fiji)', -17.853, 177.194, 'Oceania & Pacific', 'Reeling, powerful left over reef, one of the planet''s best waves.', true),
  ('Hossegor', 43.662, -1.443, 'Europe', 'France''s beach-break capital, punchy barrels over shifting sand.', true),
  ('Mundaka', 43.407, -2.698, 'Europe', 'Legendary Basque rivermouth left, a long hollow barrel when on.', true),
  ('Trestles', 33.383, -117.593, 'North America', 'High-performance Californian point with playful cobblestone peaks.', false),
  ('Bells Beach', -38.372, 144.283, 'Oceania & Pacific', 'Iconic Victorian right point, home to surfing''s oldest contest.', false),
  ('Puerto Escondido', 15.834, -97.055, 'Central America', 'The ''Mexican Pipeline'', a heavy sand-bottom barrel machine.', true),
  ('Superbank (Snapper)', -28.162, 153.55, 'Oceania & Pacific', 'Man-made sand superbank delivering absurdly long right-handers.', false),
  ('Thurso East', 58.596, -3.517, 'Europe', 'Cold, flawless right-hand reef at the top of Scotland.', false),
  ('Bundoran (The Peak)', 54.479, -8.281, 'Europe', 'Irish A-frame reef that barrels both ways.', false),
  ('Fistral Beach', 50.416, -5.1, 'Europe', 'Newquay''s famous beach break and the heart of UK surfing.', false),
  ('Lacanau', 45.0, -1.203, 'Europe', 'Long open beach break on France''s Atlantic coast.', false),
  ('La Torche', 47.838, -4.349, 'Europe', 'Exposed Breton beach break that catches loads of swell.', false),
  ('Zarautz', 43.283, -2.17, 'Europe', 'Long Basque beach break with a lively surf town behind it.', false),
  ('Guethary', 43.424, -1.609, 'Europe', 'Deep-water Basque reef that handles big Atlantic swells.', false),
  ('El Quemao', 29.14, -13.554, 'Europe', 'Lanzarote''s heavy ''Canarian Pipeline'' reef.', false),
  ('Steamer Lane', 36.951, -122.026, 'North America', 'Santa Cruz''s premier right point over rock reef.', false),
  ('Ocean Beach (SF)', 37.759, -122.511, 'North America', 'Cold, heavy San Francisco beach break with punishing paddle-outs.', false),
  ('Rincon (California)', 34.372, -119.476, 'North America', 'The ''Queen of the Coast'', a long, peeling right point.', false),
  ('Malibu (First Point)', 34.037, -118.678, 'North America', 'The classic Californian right point that defined longboarding.', false),
  ('Blacks Beach', 32.884, -117.252, 'North America', 'Powerful San Diego beach break fed by an offshore canyon.', false),
  ('The Wedge', 33.593, -117.883, 'North America', 'Freakish Newport shorebreak that wedges up against a jetty.', false),
  ('Montauk', 41.036, -71.945, 'North America', 'The end of Long Island, New York''s best-known break.', false),
  ('Cape Hatteras', 35.238, -75.529, 'North America', 'Powerful Outer Banks beach breaks facing the open Atlantic.', false),
  ('Tofino (Cox Bay)', 49.078, -125.884, 'North America', 'Cold, scenic beach break on Vancouver Island.', false),
  ('Pavones', 8.394, -83.133, 'Central America', 'One of the world''s longest lefts on Costa Rica''s south coast.', false),
  ('Playa Hermosa (CR)', 9.573, -84.633, 'Central America', 'Powerful, consistent Costa Rican beach break.', false),
  ('Salsa Brava', 9.655, -82.752, 'Central America', 'Costa Rica''s heaviest wave, a Caribbean reef barrel.', false),
  ('Rincon (Puerto Rico)', 18.36, -67.267, 'Central America', 'Puerto Rico''s winter reef and point playground.', false),
  ('Anchor Point', 30.544, -9.728, 'Africa', 'Morocco''s legendary long right point at Taghazout.', true),
  ('Taghazout (Panorama)', 30.545, -9.71, 'Africa', 'Friendly Moroccan point break in a laid-back surf village.', false),
  ('Skeleton Bay', -22.98, 14.48, 'Africa', 'A Namibian sand-bottom left that runs for nearly two kilometres.', true),
  ('Dungeons', -34.048, 18.351, 'Africa', 'Cape Town''s cold-water big-wave reef.', false),
  ('Muizenberg', -34.108, 18.47, 'Africa', 'Gentle Cape Town beach break, the city''s learners'' beach.', false),
  ('Padang Padang (Bali)', -8.811, 115.103, 'Asia', 'Bali''s ''Balinese Pipeline'', a perfect but shallow reef left.', true),
  ('Keramas (Bali)', -8.596, 115.328, 'Asia', 'High-performance right-hand reef on Bali''s east coast.', false),
  ('Desert Point (Lombok)', -8.735, 115.849, 'Asia', 'A freight-train barrelling left, one of Asia''s best.', false),
  ('G-Land (Grajagan)', -8.735, 114.36, 'Asia', 'Long, powerful Javanese jungle reef left.', false),
  ('Lagundri Bay (Nias)', 0.581, 97.741, 'Asia', 'Sumatran right-hand reef famous for its dredging barrel.', false),
  ('Arugam Bay', 6.84, 81.836, 'Asia', 'Sri Lanka''s long, mellow right point.', false),
  ('Cloud 9 (Siargao)', 9.815, 126.166, 'Asia', 'The Philippines'' signature barrelling right reef.', false),
  ('Margaret River', -33.972, 114.988, 'Oceania & Pacific', 'Powerful Western Australian reef facing the Indian Ocean.', false),
  ('Kirra', -28.17, 153.526, 'Oceania & Pacific', 'Gold Coast sand-bottom right, one of the best barrels on earth.', false),
  ('Burleigh Heads', -28.09, 153.459, 'Oceania & Pacific', 'Classic Gold Coast point wrapping around the headland.', false),
  ('Raglan (Manu Bay)', -37.821, 174.717, 'Oceania & Pacific', 'New Zealand''s famous long, peeling left point.', true),
  ('Shipsterns Bluff', -43.312, 147.883, 'Oceania & Pacific', 'Mutant Tasmanian slab reef with a notorious step.', false),
  ('Honolua Bay (Maui)', 21.015, -156.638, 'Oceania & Pacific', 'Maui''s premier right point that lights up on winter swells.', false)
ON CONFLICT (name) DO UPDATE SET
  lat = EXCLUDED.lat,
  lon = EXCLUDED.lon,
  region = EXCLUDED.region,
  description = EXCLUDED.description,
  featured = EXCLUDED.featured;
